version: "3.2"
services:
  jenkins:
    image: jenkins:alpine
     deploy:
      placement:
        constraints:
          - 'node.hostname == worker3'
    volumes:
      - /root/jenkins/data/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
