version: "3.2"
services:
  jenkins:
    image: jenkins:alpine
    volumes:
      - /root/jenkins/data/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
